// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsszxzcbqkarydztwend.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzc3p4emNicWthcnlkenR3ZW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzA2OTUsImV4cCI6MjA2NzMwNjY5NX0.Nsmhi7DAMRI_QbjzXpugeqx6jUpnFjuvd3LqfGKMoCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});